### PR TITLE
Add yarn.lock

### PR DESCRIPTION
**Pull request by wincent**
Following best practices, we should commit this to the repo to have a stable development environment:

https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all

### CODE REVIEW

**Comment by wincent** [comment]
Any reason why we shouldn't commit this to the repo, @leebyron, @asiandrummer?

(Rolled this as a PR against my fork [on top of #238 upstream](https://github.com/graphql/graphiql/pull/238) as it is somewhat RC; will send upstream if we think this is a good idea.)

**Comment by leebyron** [comment]
I don't see any problem with it. Are yarn.lock files supposed make their way to npm as well, should this pr also ensure yarn.lock is included / excluded?

**Comment by leebyron** [comment]
^ I would assume that yarn.lock files are not supposed to be on npm since this lock file includes all the dev dependencies

**Comment by wincent** [comment]
My understanding is that they *can* be included if you want, but serves no purpose, because any project using an `yarn.lock`-equipped app/library will ignore it for the purposes of dependency resolution, relying only on what `package.json` says.

**Comment by asiandrummer** [comment]
I'm okay committing it - the best practices also suggests to do so as well. Maybe we should also update the README to let people know `yarn install` is also a choice now.

**Comment by leebyron** [comment]
After a little research the prevailing wisdom is check it in, but don't distribute on npm unless your npm package is to be installed globally as a finished application and not a library.

**Pull request closed without merging**
